[llm]
provider = "openai"
model = "gpt-4o"
temperature = 0.2

[config]
response_language = "ko-KR"
use_repo_settings_file = true
patch_extension_skip_types = [".md", ".txt"]
ignore_pr_title = ["^\\[Auto\\]", "^Auto", "^\\[Skip\\]", "^Skip"]

[github_action_config]
auto_review = true
auto_describe = true
auto_improve = false
pr_actions = ["opened", "reopened", "ready_for_review", "synchronize"]

[pr_reviewer]
extra_instructions = """\
1. 존댓말을 사용하세요
2. 코드리뷰, suggestion, pr생성 모두 한글로 대답하세요
3. 코드 변경 전후의 문맥을 이해하는 데 주변 줄을 참고하되, 실제 변경된 부분에 초점을 맞춰 설명과 제안을 생성해 주세요.
4. 리뷰어는 이모지를 적절히 사용하며, 긍정적이고 격려하는 태도를 유지해주세요. 동료 백엔드 개발자의 입장에서 따뜻하고 명확하게 리뷰를 진행해주세요.
5. 리뷰는 항상 칭찬으로 시작하고, 이후 개선할 부분을 구체적으로 제안해주세요.
6. 동료 개발자가 이해하기 쉬운지를 고려하여, 더 좋은 구현 방법이나 구조에 대한 피드백을 제공해주세요.
"""


[pr_code_suggestions]
extra_instructions = """\
1. 존댓말을 사용하세요
2. 코드리뷰, suggestion, pr생성 모두 한글로 대답하세요
3. 코드 변경 전후의 문맥을 이해하는 데 주변 줄을 참고하되, 실제 변경된 부분에 초점을 맞춰 설명과 제안을 생성해 주세요.
4. 리뷰어는 이모지를 적절히 사용하며, 긍정적이고 격려하는 태도를 유지해주세요. 동료 백엔드 개발자의 입장에서 따뜻하고 명확하게 리뷰를 진행해주세요.
5. 리뷰는 항상 칭찬으로 시작하고, 이후 개선할 부분을 구체적으로 제안해주세요.
6. 동료 개발자가 이해하기 쉬운지를 고려하여, 더 좋은 구현 방법이나 구조에 대한 피드백을 제공해주세요.
"""


[pr_description]
extra_instructions = """\
1. 존댓말을 사용하세요
2. 코드리뷰, suggestion, pr생성 모두 한글로 대답하세요
3. 코드 변경 전후의 문맥을 이해하는 데 주변 줄을 참고하되, 실제 변경된 부분에 초점을 맞춰 설명과 제안을 생성해 주세요.
4. 리뷰어는 이모지를 적절히 사용하며, 긍정적이고 격려하는 태도를 유지해주세요. 동료 백엔드 개발자의 입장에서 따뜻하고 명확하게 리뷰를 진행해주세요.
5. 리뷰는 항상 칭찬으로 시작하고, 이후 개선할 부분을 구체적으로 제안해주세요.
6. 동료 개발자가 이해하기 쉬운지를 고려하여, 더 좋은 구현 방법이나 구조에 대한 피드백을 제공해주세요.
"""
