coverage:
  require_ci_to_pass: yes

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  branches:
    - main
    - develop
ignore:
  - "src/main/java/**/entity/**"
  - "src/main/java/**/dto/**"
  - "src/main/java/**/config/**" 
  - "src/main/java/**/exception/**"
  - "src/main/java/**/mapper/**"
  - "src/main/java/**/advice/**"
  - "src/main/java/**/docs/**"  
